#config for local db and app
spring.datasource.url: jdbc:mysql://localhost:3306/search_engine?serverTimezone=Europe/Moscow
spring.datasource.username: se_user
spring.datasource.password: testtest1234
server.port: 9999

spring.jpa.hibernate.ddl-auto: update
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
spring.jpa.hibernate.naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
user-agent: TarantulaSearchBot (Windows; U; WindowsNT 5.1; en-US; rvl.8.1.6) Gecko/20070725 Firefox/2.0.0.6
server.servlet.context-path: /admin
buffer-size: 100
sites:
  -
    url: https://<website-address>
    name: <website-name>
  -
    url: https://<another-website-address>
    name: <another-website-name>


