spring.datasource.url: jdbc:${CLEARDB_DATABASE_URL:mysql://localhost:3306/search_engine}
#spring.datasource.url: "jdbc:mysql://eu-cdbr-west-02.cleardb.net/heroku_0ac422f96a2f84b?reconnect=true&useUnicode=true&characterEncoding=UTF-8"
server.port: ${PORT:8080}
server.tomcat.max-threads: 1
spring:
  datasource:
    hikari:
      maximum-pool-size: 5
#spring.datasource.username: baae81ca55f9a0
#spring.datasource.password: 79447fdc
#spring.datasource.url: jdbc:mysql://localhost:3306/search_engine?serverTimezone=Europe/Moscow
#spring.datasource.username: se_user
#spring.datasource.password: testtest1234
#server.port: 9999

spring.jpa.hibernate.ddl-auto: update
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
spring.jpa.hibernate.naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
user-agent: TarantulaSearchBot (Windows; U; WindowsNT 5.1; en-US; rvl.8.1.6) Gecko/20070725 Firefox/2.0.0.6
server.servlet.context-path: /admin
buffer-size: 40
sites:
#  -
#    url: https://www.svetlovka.ru
#    name: Центральная городская молодежная библиотека им. М. А. Светлова
#  -
#    url: https://www.lutherancathedral.ru
#    name: Собор Петра и Павла
  -
    url: https://nikoartgallery.com
    name: Галерея искусств Niko
#  -
#    url: https://ipfran.ru
#    name: ИПФ РАН

