spring.datasource.url: jdbc:mysql://b9e7217e3db42f:95f5740e@eu-cdbr-west-02.cleardb.net/heroku_f5959d4817a4109?reconnect=true&useUnicode=true&characterEncoding=utf-8
#spring.datasource.username: b9e7217e3db42f
#spring.datasource.password: 95f5740e

spring.jpa.hibernate.ddl-auto: update
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
spring.jpa.hibernate.naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
user-agent: TarantulaSearchBot (Windows; U; WindowsNT 5.1; en-US; rvl.8.1.6) Gecko/20070725 Firefox/2.0.0.6
server.servlet.context-path: /admin
server.port: 9999

sites:
  -
    url: https://www.svetlovka.ru
    name: Центральная городская молодежная библиотека им. М. А. Светлова
#  -
#    url: https://www.lutherancathedral.ru
#    name: Собор Петра и Павла
  -
    url: https://nikoartgallery.com
    name: Галерея искусств Niko
#  -
#    url: https://ipfran.ru
#    name: ИПФ РАН

spring.flyway.baseline-on-migrate: true
spring.flyway.locations=classpath: src/main/resources/db/migration
